In [17]:
import pandas as pd

In [18]:

df = pd.read_csv(r"C:\Users\asus\Downloads\Airport_Operations_20k_Realistic.csv")

df["Flight_ID"] = df["Flight_ID"].astype(str)
print("Data Types:")
print(df.dtypes)

for col in df.columns:
    if df[col].dtype == 'object':
        try:
            pd.to_numeric(df[col])
            print(f"{col} may contain numeric values stored as text.")
        except:
            pass

df["Flight_Date"] = pd.to_datetime(df["Flight_Date"],errors="coerce")

invalid_dates = df[df["Flight_Date"].isnull()]

print("\nInvalid Flight_Date Records:")
print(invalid_dates[["Flight_Date"]])

# Check Month column
print("\nUnique Month Values:")
print(df["Month"].unique())

Data Types:
Flight_ID                        object
Airline                          object
Origin                           object
Destination                      object
Aircraft_Type                    object
Terminal                         object
Gate                             object
Weather_Condition                object
Flight_Date                      object
Month                            object
Scheduled_Departure              object
Scheduled_Arrival                object
Status                           object
Gate_Delay_Min                    int64
Fuel_Delay_Min                    int64
Baggage_Delay_Min                 int64
Catering_Delay_Min                int64
Passenger_Transfer_Delay_Min      int64
Cleaning_Delay_Min                int64
Security_Delay_Min                int64
Maintenance_Delay_Min             int64
ATC_Delay_Min                     int64
Total_Delay_Min                   int64
Departure_Delay_Min               int64
Arrival_Delay_Min                 int64
Passenger_Count                   int64
Load_Factor (%)                 float64
Ground_Staff_Count                int64
Baggage_Count                     int64
Fuel_Quantity_Liters              int64
Gate_Occupancy_Min                int64
Turnaround_Time_Min               int64
Actual_Departure                 object
Actual_Arrival                   object
Delay_Reason                     object
dtype: object

Invalid Flight_Date Records:
Empty DataFrame
Columns: [Flight_Date]
Index: []

Unique Month Values:
['February' 'June' 'April' 'October' 'September' 'May' 'December'
 'January' 'March' 'July' 'August' 'November']

In [19]:
invalid_baggage = df[df["Baggage_Delay_Min"] < 0]

invalid_total = df[df["Total_Delay_Min"] < 0]


invalid_passenger = df[
    (df["Passenger_Count"] <= 0) |
    (df["Passenger_Count"] > 850)
]

print("Invalid Baggage Delay:", len(invalid_baggage))
print("Invalid Total Delay:", len(invalid_total))
print("Invalid Passenger Count:", len(invalid_passenger))

Invalid Baggage Delay: 0
Invalid Total Delay: 0
Invalid Passenger Count: 0

In [20]:
print("Aircraft Types")
print(df["Aircraft_Type"].value_counts())

print("\nStatus Values")
print(df["Status"].value_counts())

Aircraft Types
Aircraft_Type
B787    3381
A350    3369
A320    3335
A321    3314
B737    3314
B777    3287
Name: count, dtype: int64

Status Values
Status
On Time      15089
Delayed       3912
Cancelled      999
Name: count, dtype: int64

In [21]:

report = []


report.append("Missing Values")
report.append(str(df.isnull().sum()))
report.append("\n")


duplicates = df.duplicated(subset="Flight_ID").sum()
report.append(f"Duplicate Flight_IDs : {duplicates}")
report.append("\n")

report.append("Data Types")
report.append(str(df.dtypes))
report.append("\n")


invalid_baggage = len(df[df["Baggage_Delay_Min"] < 0])
invalid_total = len(df[df["Total_Delay_Min"] < 0])
invalid_passenger = len(df[(df["Passenger_Count"] <= 0) | (df["Passenger_Count"] > 850)])

report.append(f"Invalid Baggage Delay : {invalid_baggage}")
report.append(f"Invalid Total Delay : {invalid_total}")
report.append(f"Invalid Passenger Count : {invalid_passenger}")
report.append("\n")

report.append("Aircraft Types")
report.append(str(df["Aircraft_Type"].value_counts()))

report.append("\nStatus")
report.append(str(df["Status"].value_counts()))


with open("Data_Profiling_Report.txt", "w") as file:
    file.write("\n".join(report))

print("Data Profiling Report Created Successfully.")

Data Profiling Report Created Successfully.

In [22]:
df.head()

,Flight_ID,Airline,Origin,Destination,Aircraft_Type,Terminal,Gate,Weather_Condition,Flight_Date,Month,...,Passenger_Count,Load_Factor (%),Ground_Staff_Count,Baggage_Count,Fuel_Quantity_Liters,Gate_Occupancy_Min,Turnaround_Time_Min,Actual_Departure,Actual_Arrival,Delay_Reason
0,FL100000,Akasa Air,CCU,BOM,B777,T3,G9,Rain,2025-02-09,February,...,256,83.46,23,312,60774,53,100,2025-02-09 15:34:00,2025-02-09 17:18:00,No Delay
1,FL100001,Vistara,BOM,MAA,B777,T2,G18,Clear,2025-06-17,June,...,59,95.21,22,75,30079,74,100,2025-06-17 09:15:00,2025-06-17 13:38:00,No Delay
2,FL100002,Qatar Airways,MAA,CCU,B787,T1,G43,Clear,2025-04-19,April,...,138,65.68,16,191,27653,73,108,2025-04-19 10:26:00,2025-04-19 13:54:00,No Delay
3,FL100003,Akasa Air,HYD,DEL,B777,T2,G24,Clear,2025-10-08,October,...,253,83.22,22,274,67394,102,105,2025-10-08 20:29:00,2025-10-08 23:29:00,No Delay
4,FL100004,SpiceJet,BLR,CCU,A321,T1,G27,Clear,2025-02-25,February,...,63,94.33,8,86,63337,113,117,2025-02-25 23:21:00,2025-02-26 01:17:00,Maintenance

In [23]:
print("Data Types:")
print(df.dtypes)

Data Types:
Flight_ID                               object
Airline                                 object
Origin                                  object
Destination                             object
Aircraft_Type                           object
Terminal                                object
Gate                                    object
Weather_Condition                       object
Flight_Date                     datetime64[ns]
Month                                   object
Scheduled_Departure                     object
Scheduled_Arrival                       object
Status                                  object
Gate_Delay_Min                           int64
Fuel_Delay_Min                           int64
Baggage_Delay_Min                        int64
Catering_Delay_Min                       int64
Passenger_Transfer_Delay_Min             int64
Cleaning_Delay_Min                       int64
Security_Delay_Min                       int64
Maintenance_Delay_Min                    int64
ATC_Delay_Min                            int64
Total_Delay_Min                          int64
Departure_Delay_Min                      int64
Arrival_Delay_Min                        int64
Passenger_Count                          int64
Load_Factor (%)                        float64
Ground_Staff_Count                       int64
Baggage_Count                            int64
Fuel_Quantity_Liters                     int64
Gate_Occupancy_Min                       int64
Turnaround_Time_Min                      int64
Actual_Departure                        object
Actual_Arrival                          object
Delay_Reason                            object
dtype: object

In [24]:
df["Year"] = df["Flight_Date"].dt.year
df["Day"]=df["Flight_Date"].dt.year
# Convert to datetime (if not already)
df["Actual_Departure"] = pd.to_datetime(df["Actual_Departure"])
df["Actual_Arrival"] = pd.to_datetime(df["Actual_Arrival"])

# Create new time columns
df["Departure_Time"] = df["Actual_Departure"].dt.time
df["Arrival_Time"] = df["Actual_Arrival"].dt.time
df["Departure_Hour"] = df["Actual_Departure"].dt.hour
df["Departure_Minute"] = df["Actual_Departure"].dt.minute

df["Arrival_Hour"] = df["Actual_Arrival"].dt.hour
df["Arrival_Minute"] = df["Actual_Arrival"].dt.minute
# Display the result
print(df[["Actual_Departure", "Departure_Time",
          "Actual_Arrival", "Arrival_Time"]].head())

     Actual_Departure Departure_Time      Actual_Arrival Arrival_Time
0 2025-02-09 15:34:00       15:34:00 2025-02-09 17:18:00     17:18:00
1 2025-06-17 09:15:00       09:15:00 2025-06-17 13:38:00     13:38:00
2 2025-04-19 10:26:00       10:26:00 2025-04-19 13:54:00     13:54:00
3 2025-10-08 20:29:00       20:29:00 2025-10-08 23:29:00     23:29:00
4 2025-02-25 23:21:00       23:21:00 2025-02-26 01:17:00     01:17:00

In [25]:
df.head()

,Flight_ID,Airline,Origin,Destination,Aircraft_Type,Terminal,Gate,Weather_Condition,Flight_Date,Month,...,Actual_Arrival,Delay_Reason,Year,Day,Departure_Time,Arrival_Time,Departure_Hour,Departure_Minute,Arrival_Hour,Arrival_Minute
0,FL100000,Akasa Air,CCU,BOM,B777,T3,G9,Rain,2025-02-09,February,...,2025-02-09 17:18:00,No Delay,2025,2025,15:34:00,17:18:00,15.0,34.0,17.0,18.0
1,FL100001,Vistara,BOM,MAA,B777,T2,G18,Clear,2025-06-17,June,...,2025-06-17 13:38:00,No Delay,2025,2025,09:15:00,13:38:00,9.0,15.0,13.0,38.0
2,FL100002,Qatar Airways,MAA,CCU,B787,T1,G43,Clear,2025-04-19,April,...,2025-04-19 13:54:00,No Delay,2025,2025,10:26:00,13:54:00,10.0,26.0,13.0,54.0
3,FL100003,Akasa Air,HYD,DEL,B777,T2,G24,Clear,2025-10-08,October,...,2025-10-08 23:29:00,No Delay,2025,2025,20:29:00,23:29:00,20.0,29.0,23.0,29.0
4,FL100004,SpiceJet,BLR,CCU,A321,T1,G27,Clear,2025-02-25,February,...,2025-02-26 01:17:00,Maintenance,2025,2025,23:21:00,01:17:00,23.0,21.0,1.0,17.0

In [26]:

df.to_csv("Airport_Operations_Dataset_Cleaned.csv", index=False)

print("File successfully saved as CSV!")

File successfully saved as CSV!